#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("norsu.ass.Resource", IsApplication=true)]

namespace norsu.ass
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NetworkCommsDotNet.Resource.String.ApplicationName = global::norsu.ass.Resource.String.ApplicationName;
			global::NetworkCommsDotNet.Resource.String.Hello = global::norsu.ass.Resource.String.Hello;
			global::ProtobufSerializer.Resource.String.ApplicationName = global::norsu.ass.Resource.String.ApplicationName;
			global::ProtobufSerializer.Resource.String.Hello = global::norsu.ass.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_comment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_star_half = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_arrow_drop_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_arrow_drop_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_check_circle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_comment = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_error = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_thumb_down = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_thumb_up = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_thumbs_up_down = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int norsu = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int action_dislike = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int action_like = 2131165220;
			
			// aapt resource value: 0x7f070010
			public const int anonymous = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int body = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int comment = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int dislike = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int like = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int likes = 2131165190;
			
			// aapt resource value: 0x7f070022
			public const int listView = 2131165218;
			
			// aapt resource value: 0x7f070012
			public const int login = 2131165202;
			
			// aapt resource value: 0x7f070019
			public const int message = 2131165209;
			
			// aapt resource value: 0x7f070001
			public const int name = 2131165185;
			
			// aapt resource value: 0x7f070023
			public const int newSuggestion = 2131165219;
			
			// aapt resource value: 0x7f07000f
			public const int nickName = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int officeLongName = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int officePicture = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int officeRating = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int officeRatingCount = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int officeShortName = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int officeSuggestions = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int password = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int picture = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int privateCheckbox = 2131165216;
			
			// aapt resource value: 0x7f070003
			public const int progress = 2131165187;
			
			// aapt resource value: 0x7f070018
			public const int rating = 2131165208;
			
			// aapt resource value: 0x7f070011
			public const int register = 2131165201;
			
			// aapt resource value: 0x7f07001c
			public const int reviews = 2131165212;
			
			// aapt resource value: 0x7f07000c
			public const int send = 2131165196;
			
			// aapt resource value: 0x7f070021
			public const int submit = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int submitProgress = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int suggestions = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int userName = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int userPicture = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int userType = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int userView = 2131165197;
			
			// aapt resource value: 0x7f07001b
			public const int viewAllReviews = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int viewAllSuggestions = 2131165213;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommentRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Comments = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Offices = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OfficesRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RatingRow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Ratings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RatingsTab = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SuggestionRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SuggestionsTab = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int SuggestionMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Theme_ActionBar = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Theme_FullScreen = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Theme_Splash = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
