#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("norsu.ass.Resource", IsApplication=true)]

namespace norsu.ass
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NetworkCommsDotNet.Resource.String.ApplicationName = global::norsu.ass.Resource.String.ApplicationName;
			global::NetworkCommsDotNet.Resource.String.Hello = global::norsu.ass.Resource.String.Hello;
			global::ProtobufSerializer.Resource.String.ApplicationName = global::norsu.ass.Resource.String.ApplicationName;
			global::ProtobufSerializer.Resource.String.Hello = global::norsu.ass.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_comment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_star_half = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int norsu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int anonymous = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int fragmentContainer = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int login = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int message = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int name = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int nickName = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int password = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int privateCheckbox = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int progress = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int rating = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int register = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int submit = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int submitProgress = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int userName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int userView = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Offices = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OfficesRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RatingRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Ratings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RatingsTab = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Theme_ActionBar = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Theme_FullScreen = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Theme_Splash = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
